# Generated by Django 6.1.1 on 2026-09-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_data',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
